# Generated by Django 5.2 on 2025-04-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConsultoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagen_url', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('desbloqueado', models.BooleanField(default=False)),
                ('completado', models.BooleanField(default=False)),
            ],
        ),
    ]
